### ISSUE TITLE
The unit should be character instead of pixel

### ISSUE THREAD

**Issue by lijunle** [romainwn/hyper-window-size#2]
I am setting the `width` and `height` reference the number during drag and drop, then I notice the number for setting is pixel, not number of characters.

It is making more sense to set the numbers referencing the following two numbers.

![image](https://user-images.githubusercontent.com/1296500/42689360-8aae1df2-86d2-11e8-8021-2b289dc74bfc.png)

**Comment by romainlq** [comment]
Agree, I'll try to take a look at it, but if you have any extra free time, feel free to submit a PR ! :smile:

**Comment by romainlq** [comment]
Fixed with 0.3.5 (finally  thanks to @iZanfir 😅 )
