### ISSUE TITLE
Set height/width without touching startX/startY

### ISSUE THREAD

**Issue by lijunle** [romainwn/hyper-window-size#3]
Is it possible to set `height`/`width` values without touching `startX`/`startY`? I want the OS to determine the opening position.

**Comment by romainlq** [comment]
I will try to take a look at it in the next few days !
I totally agree with you :+1:

**Comment by romainlq** [comment]
Sorry, I did not really got a chance to take a look at it this summer, maybe someone will try to tackle this issue during Hacktoberfest

**Comment by rollecode** [comment]
I'd also need this, thx!
